### PR TITLE
BAU Used govuk-lint-ruby to auto-fix complaints

### PR DESCRIPTION
**Pull request by j-maynard**
They've updated govuk-lint-ruby to complain about string literals.
This PR is to address its complaints.

### CODE REVIEW

**Comment by brenetic** [comment]
Defo with J-Snoop on this one. We should override this in the `rubocop.yml`. I might go ask with this was turned on.

**Comment by j-maynard** [comment]
All in favour say aye.... AYE!

**Comment by brenetic** [comment]
@Rosa-Fox is right, The O Father (@jkunle) will most certainly not be happy.

**Comment by jkunle** [comment]
When I started ruby my instinct was to always use double quotes, but Chris Holmes advised my otherwise. Personally I prefer double quotes but this appears to be against ruby style guide, am not bothered by this as long as we are consistent.

**Comment by issyl0** [comment]
The reasoning was outlined [in this PR](https://github.com/alphagov/govuk-lint/pull/124).

**Pull request closed without merging**
