### PR TITLE
EnWrvhcz: Send a notification email when user changes or resets password

### PR DESCRIPTION
**Pull request by jakubmiarka**
A notification email is now sent when user changes/resets their password.

### CODE REVIEW

**Comment by AmritSidhu** [comment]
Tested with changing name and I successfully received an email, but im not receiving any emails when changing my password

**Comment by jakubmiarka** [comment]
> Tested with changing name and I successfully received an email, but im not receiving any emails when changing my password. Rosa also did the journey and did not receive an email

@AmritSidhu @Rosa-Fox There was a typo in the template, it was expecting "first name" but we're passing "first_name", can you re-check?

**Comment by AmritSidhu** [comment]
Can confirm that the changes in the other PR does make this work :)

**Comment by jakubmiarka** [comment]
> Can confirm that the changes in the other PR makes this work :)

Thanks for checking! I'll merge it then...

**Pull request merged**
