### PR TITLE
Lambderize

### PR DESCRIPTION
**Pull request by chrisholmes**

### CODE REVIEW

**Comment by brenetic** [comment]
@j-maynard you ever gonna close this? 😛

**Comment by jakubmiarka** [comment]
> @j-maynard you ever gonna close this? 😛

close? I would expect you @brenetic wanted it merged 😛

**Comment by brenetic** [comment]
😆  this is true!

**Comment by j-maynard** [comment]
I have talked to @brenetic and we think we can just close this at this point.  It was an interesting experiment and we have PR for information if we ever want to go down this route.

**Pull request closed without merging**
